<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="3" failed="4" skipped="0">
  <reporter-output>
    <line>
      <![CDATA['Please input Email' and 'Please input Email' is  matching]]>
    </line>
    <line>
      <![CDATA['Please confirm you are above 18 years old!' and 'Please confirm you are above 18 years old!' is  matching]]>
    </line>
    <line>
      <![CDATA['Please input Name' and 'Please input Name' is  matching]]>
    </line>
    <line>
      <![CDATA['Please select size' and 'Please selet size' is not matching]]>
    </line>
  </reporter-output>
  <suite started-at="2024-06-26T18:27:12Z" name="Default suite" finished-at="2024-06-26T18:27:53Z" duration-ms="40534">
    <groups>
    </groups>
    <test started-at="2024-06-26T18:27:12Z" name="Default test" finished-at="2024-06-26T18:27:53Z" duration-ms="40534">
      <class name="bobchos.bar.Test.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:12Z" name="launchApplication" finished-at="2024-06-26T18:27:17Z" duration-ms="4923" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="assertEmailFieldError()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:17Z" name="assertEmailFieldError" finished-at="2024-06-26T18:27:18Z" duration-ms="829" status="PASS">
          <reporter-output>
            <line>
              <![CDATA['Please input Email' and 'Please input Email' is  matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- assertEmailFieldError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:18Z" name="tearDown" finished-at="2024-06-26T18:27:18Z" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:18Z" name="launchApplication" finished-at="2024-06-26T18:27:22Z" duration-ms="4077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="assertIsAdultFieldError()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:22Z" name="assertIsAdultFieldError" finished-at="2024-06-26T18:27:23Z" duration-ms="896" status="PASS">
          <reporter-output>
            <line>
              <![CDATA['Please confirm you are above 18 years old!' and 'Please confirm you are above 18 years old!' is  matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- assertIsAdultFieldError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:23Z" name="tearDown" finished-at="2024-06-26T18:27:23Z" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:23Z" name="launchApplication" finished-at="2024-06-26T18:27:27Z" duration-ms="4039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="assertNameFieldError()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:27Z" name="assertNameFieldError" finished-at="2024-06-26T18:27:28Z" duration-ms="680" status="PASS">
          <reporter-output>
            <line>
              <![CDATA['Please input Name' and 'Please input Name' is  matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- assertNameFieldError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:28Z" name="tearDown" finished-at="2024-06-26T18:27:28Z" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:28Z" name="launchApplication" finished-at="2024-06-26T18:27:32Z" duration-ms="4095" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="assertQuantityFieldError()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:32Z" name="assertQuantityFieldError" finished-at="2024-06-26T18:27:33Z" duration-ms="683" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please input Quantity] but found [Please input Name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please input Quantity] but found [Please input Name]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at bobchos.bar.Test.ErrorValidationTest.assertQuantityFieldError(ErrorValidationTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertQuantityFieldError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:33Z" name="tearDown" finished-at="2024-06-26T18:27:33Z" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:33Z" name="launchApplication" finished-at="2024-06-26T18:27:37Z" duration-ms="4127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="assertSizeFieldError()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:37Z" name="assertSizeFieldError" finished-at="2024-06-26T18:27:38Z" duration-ms="666" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please select size] but found [Please selet size]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please select size] but found [Please selet size]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at bobchos.bar.TestComponents.BaseTest.Report(BaseTest.java:132)
at bobchos.bar.Test.ErrorValidationTest.assertSizeFieldError(ErrorValidationTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA['Please select size' and 'Please selet size' is not matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- assertSizeFieldError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:38Z" name="tearDown" finished-at="2024-06-26T18:27:38Z" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:38Z" name="launchApplication" finished-at="2024-06-26T18:27:42Z" duration-ms="4128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="checkQuantityNegative()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:42Z" name="checkQuantityNegative" finished-at="2024-06-26T18:27:45Z" duration-ms="3079" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at bobchos.bar.Test.ErrorValidationTest.checkQuantityNegative(ErrorValidationTest.java:196)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkQuantityNegative -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:45Z" name="tearDown" finished-at="2024-06-26T18:27:46Z" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:46Z" name="launchApplication" finished-at="2024-06-26T18:27:50Z" duration-ms="4151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="invalidEmailInput()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:50Z" name="invalidEmailInput" finished-at="2024-06-26T18:27:53Z" duration-ms="3033" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at bobchos.bar.Test.ErrorValidationTest.invalidEmailInput(ErrorValidationTest.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmailInput -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:bobchos.bar.Test.ErrorValidationTest@58bf8650]" started-at="2024-06-26T18:27:53Z" name="tearDown" finished-at="2024-06-26T18:27:53Z" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- bobchos.bar.Test.ErrorValidationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
